name: Tests
on: push
jobs:
  lesson-0-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: cd ./lesson-0 && npm install
    - name: Run tests
      run: cd ./lesson-0 && npm run test